update rtd yaml

diff --git a/docs/tools/.readthedocs.yaml b/docs/tools/.readthedocs.yaml
--- a/docs/tools/.readthedocs.yaml
+++ b/docs/tools/.readthedocs.yaml
@@ -9,10 +9,21 @@ version: 2
 build:
   os: ubuntu-22.04
   tools:
-    python: "3.11"
+    python: "3.12"
   jobs:
     pre_build:
-      - cp -r docs/src/* docs/tools/
+      - cp -r docs/src/* docs/tools/    
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
+        then
+          exit 183;
+        fi
+  
       
 # Build documentation in the docs/ directory with Sphinx
 sphinx:
