update config and build tools

diff --git a/docs/canonicalk8s/.readthedocs.yaml b/docs/canonicalk8s/.readthedocs.yaml
--- a/docs/canonicalk8s/.readthedocs.yaml
+++ b/docs/canonicalk8s/.readthedocs.yaml
@@ -9,17 +9,26 @@ version: 2
 build:
   os: ubuntu-22.04
   tools:
-    python: "3.11"
+    python: "3.12"
   jobs:
-    pre_install:
-      - python3 .sphinx/build_requirements.py
-      - git fetch --unshallow || true
-
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      #
+      # https://docs.readthedocs.io/en/latest/build-customization.html#cancel-build-based-on-a-condition
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
+        then
+          exit 183;
+        fi
+    pre_build:
+      - cp -r docs/src/* docs/tools/
+      
 # Build documentation in the docs/ directory with Sphinx
 sphinx:
   builder: dirhtml
-  configuration: conf.py
-  fail_on_warning: true
+  configuration: docs/canonicalk8s/conf.py
 
 # If using Sphinx, optionally build your docs in additional formats such as PDF
 formats:
@@ -28,4 +37,5 @@ formats:
 # Optionally declare the Python requirements required to build your docs
 python:
    install:
-   - requirements: .sphinx/requirements.txt
+   - requirements: docs/tools/.sphinx/requirements.txt
+
