update starter pack framework

diff --git a/.github/workflows/docs-checks.yml b/.github/workflows/docs-checks.yml
--- a/.github/workflows/docs-checks.yml
+++ b/.github/workflows/docs-checks.yml
@@ -9,25 +9,30 @@ permissions:
   contents: read
 
 jobs:
-  doc-checks:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  documentation-checks:
+    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
+    with:
+      working-directory: "docs/canonicalk8s"
+      fetch-depth: 0
+  # doc-checks:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Install vale
-        run: sudo snap install vale
-      - id: spell-check
-        name: Spell Check
-        run: vale --glob='*.{md,txt,rst}' .
-        working-directory: docs/canonicalk8s
+  #     - name: Install vale
+  #       run: sudo snap install vale
+  #     - id: spell-check
+  #       name: Spell Check
+  #       run: vale --glob='*.{md,txt,rst}' .
+  #       working-directory: docs/canonicalk8s
 
-      - name: Link Check
-        id: linkcheck-step
-        if: success() || failure()
-        uses: canonical/documentation-workflows/linkcheck@main
-        with:
-          working-directory: docs/canonicalk8s
+  #     - name: Link Check
+  #       id: linkcheck-step
+  #       if: success() || failure()
+  #       uses: canonical/documentation-workflows/linkcheck@main
+  #       with:
+  #         working-directory: docs/canonicalk8s
 
       # - name: Inclusive Language Check
       #   id: woke-step
