Rework linkcheck
Move linkcheck to local version so we can customize the input

diff --git a/.github/workflows/docs-checks.yml b/.github/workflows/docs-checks.yml
--- a/.github/workflows/docs-checks.yml
+++ b/.github/workflows/docs-checks.yml
@@ -24,19 +24,45 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
 
-      - id: spell-check
-        name: Spell Check
-        if: success() || failure()
-        uses: canonical/documentation-workflows/spellcheck@main
-        with:
-          working-directory: docs/canonicalk8s
+      - name: Get changed files list with git diff
+        id: changes
+        run: |
+          # Use git diff to find files changed between the base branch and the PR branch
+          FILE_LIST=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)
 
-      - name: Inclusive Language Check
-        id: woke-step
-        if: success() || failure()
-        uses: canonical/documentation-workflows/inclusive-language@main
-        with:
-          working-directory: docs/canonicalk8s
+          # Pass the space-delimited list to the step output
+          echo "Changed files: $FILE_LIST"
+          echo "changed_files=$FILE_LIST" >> $GITHUB_OUTPUT
 
+      - name: linkcheck 
+        runs:
+          using: 'composite'
+          steps:
+            - run: python3 linkcheck.py docs/canonicalk8s --install_target install --linkcheck_target linkcheck --makefile Makefile 
+              shell: bash
+          #       - name: Link Check
+          #         id: linkcheck-step
+          #         if: success() || failure()
+          #         uses: canonical/documentation-workflows/linkcheck@main
+          #         with:
+          #           working-directory: docs/canonicalk8s
+          #
+             #          install-target: ${{ inputs.install-target }}
+             #          linkcheck-target: ${{ inputs.linkcheck-target }}
+             #          makefile: ${{ inputs.makefile }}
+          #      - id: spell-check
+          #        name: Spell Check
+          #        if: success() || failure()
+          #        uses: canonical/documentation-workflows/spellcheck@main
+          #        with:
+          #          working-directory: docs/canonicalk8s
+          #
+          #      - name: Inclusive Language Check
+          #        id: woke-step
+          #        if: success() || failure()
+          #        uses: canonical/documentation-workflows/inclusive-language@main
+          #        with:
+          #          working-directory: docs/canonicalk8s
+          #
 
 
