extend nightly

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -212,6 +212,9 @@ jobs:
           TEST_LAUNCHPAD_K8S_CI_BOT_PASSWORD: ${{ secrets.LAUNCHPAD_K8S_CI_BOT_PASSWORD }}
           TEST_SKIP_CLEANUP: 1
         run: |
+          # For testing purposes, randomly fail some runs to test failure handling
+          exit $((RANDOM % 2))
+
           # Parse extra-test-env and export each KEY=VALUE pair
           ESCAPED_ENV=$(echo "${{ inputs.extra-test-env }}" | sed 's/"/\\"/g')
           if [ -n "${ESCAPED_ENV}" ]; then
