feat: Reject k8s-dqlite upgrades for 1.36+

diff --git a/snap/hooks/post-refresh b/snap/hooks/post-refresh
--- a/snap/hooks/post-refresh
+++ b/snap/hooks/post-refresh
@@ -3,6 +3,13 @@
 
 k8s::common::setup_env
 
+# Reject upgrade if deprecated k8s-dqlite datastore is used.
+if [ -d "$SNAP_COMMON/var/lib/k8s-dqlite" ]; then
+  echo "ERROR: k8s-dqlite is not supported anymore in version 1.36 and later."
+  echo "Either stay on version 1.35 or deploy a new cluster with etcd as the datastore."
+  exit 1
+fi
+
 # Indicate that an update has been performed.
 # Many actions require k8sd to be active which is not
 # the case in the snap hook. Hence, we use a lock file
